## 网站配置
logo:
  ## 网站名称
  title: 小初高中英语单词学习系统
  ## 网站图标
  image: admin/images/logo.png
## 菜单配置
menu:
  ## 菜单数据来源
  data: /system/api/user/menu
  ## 是否同时只打开一个菜单目录
  accordion: false
  ## 是否开启多系统菜单模式
  control: false
  ## 默认选中的菜单项
  select: 18
  ## 是否开启异步菜单，false 时 data 属性设置为菜单数据，false 时为 json 文件或后端接口
  async: true
## 视图内容配置
tab:
  ## 是否开启多选项卡
  muiltTab: true
  ## 切换选项卡时，是否刷新页面状态
  keepState: true
  ## 最大可打开的选项卡数量
  tabMax: 30
  ## Tab 记忆
  session: true
  ## 默认选项卡数据
  index:
    ## 标识 ID , 建议与菜单项中的 ID 一致
    id: 18
    ## 页面地址
    href: /english/dashboard
    ## 标题
    title: 首页
## 主题配置
theme:
  ## 默认主题色，对应 colors 配置中的 ID 标识
  defaultColor: "1"
  ## 默认的菜单主题 {dark-theme: 深色(黑), light-theme: 浅色(白), routine-theme: 常规(蓝)}
  defaultMenu: dark-theme
  ## 标题主题色
  titleColor: "#1890ff"
  ## 是否允许用户切换主题，false 时关闭自定义主题面板
  allowCustom: true
## 供选择的主题色配置列表
colors:
  - id: "1"
    color: "#1890ff"
  - id: "2"
    color: "#437aae"
  - id: "3"
    color: "#36b368"
  - id: "4"
    color: "#ff4401"
  - id: "5"
    color: "#e1251b"
  - id: "6"
    color: "darkgray"
## 主题面板的链接列表配置
#links:
#  - icon: layui-icon layui-icon-website
#    title: 官方网站
#    href: http://www.pearadmin.com
#  - icon: layui-icon layui-icon-read
#    title: 开发文档
#    href: http://www.pearadmin.com/doc/
#  - icon: layui-icon layui-icon-fonts-code
#    title: 开源地址
#    href: https://gitee.com/pear-admin/Pear-Admin-Layui
#  - icon: layui-icon layui-icon-survey
#    title: 问答社区
#    href: http://forum.pearadmin.com/
## 其他配置
other:
  ## 主页动画时长
  keepLoad: 1200
  ## 布局顶部主题
  autoHead: false
header:
  ## 站内消息，数据来源，通过 false 设置关闭
  message: system/notice/notice
